version: '3.4'

services:
  configurationsqlitecrudservice:
    image: ${DOCKER_REGISTRY-}configurationsqlitecrudservice
    build:
      context: .
      dockerfile: ConfigurationSqliteCRUDService/Dockerfile
    ports:
        - 5200:80

  loggingservice:
    image: ${DOCKER_REGISTRY-}loggingservice
    build:
      context: .
      dockerfile: LoggingService/Dockerfile
    ports:
        - 5230:80